<div id="top" class="clear">
	<form method="post" action="/friend/index/type/<?php echo $this->type ?>" id="friendsForm">
		<h1>
			<a class="active" href="/friend/index">Search friends</a><span> or</span>
			<a href="/friend/invite">Invite friends</a>
		</h1>
		<input type="text" autocomplete="off" class="text action <?php if ($this->name == null):?>tooltip<?php endif;?>" <?php if ($this->name == null):?>onfocus="Click.clear(this);"<?php endif;?> name="name" value="<?php if ($this->name == null):?>Search by name<?php else:?><?php echo $this->name?><?php endif;?>" />
		<a class="search" href="javascript:;" onclick="$('#friendsForm').submit()"></a>
		<div class="shareAction">
			<input type="submit" class="button right"  value="Search"/>
		</div>
	</form>
	<div class="tabs">
		<ul>
			<li<?php if ($this->type == 'following' || $this->type == ''):?> class="active"<?php endif;?>><a href="/friend">Whom I follow</a></li>
			<li<?php if ($this->type == 'followers'):?> class="active"<?php endif;?>><a href="/friend/index/type/followers">Following me</a></li>
			<li<?php if ($this->type == 'all-users'):?> class="active"<?php endif;?>><a href="/friend/index/type/all-users">All TB users</a></li>
		</ul>
	</div>
</div>

<div id="friends">
	<?php echo $this->action('posts', 'friend', null, array (
		'type' => $this->type,
		'name' => $this->name,
	));?>
</div>

<div class="block clear noBord">
	<div class="more">
		<a href="javascript:;" id="load-more">Load More Users</a>
	</div>
</div>

<script type="text/javascript">
	Pager.init('#friends', '/friend/posts/type/<?php echo $this->type?>/name/<?php echo $this->name?>');
</script>