<div class="block clear noBord">
	<?php foreach ($this->users as $user): /* @var $user \Entity\User */?>
		<div class="blockElement">
			<div class="thumbnail">
				<?php if ($user->getProfileImageUrl() != null):?>
					<img alt="" src="<?php echo $user->getProfileImageUrl()?>" />
				<?php endif;?>
			</div>
			<div class="info">
				<p class="name"><a href="/user/profile/id/<?php echo $user->getId()?>"><?php echo $user->getName()?></a></p>
				<?php if (count($user->getSports()) > 0):?>
					<p>
						<?php foreach ($user->getSports() as $i => $sport):?>
							<?php if ($i == 0):?>, <?php endif;?><?php echo $sport->getName()?>
						<?php endforeach;?>
					</p>
				<?php endif;?>
				<p><?php echo $user->getTrainingPlans()->count()?> Workout plans</p>
			</div>
		</div>
	<?php endforeach;?>
</div>