<?php echo $this->action('global', 'workout')?>

<?php echo $this->action('sets', 'workout', null, array (
	'type' => $this->type,
	'name' => $this->name,
	'event' => $this->event,
	'distance' => $this->distance,
	'search' => $this->search,
))?>

<div id="top" class="clear" style="padding-bottom:10px;">
	<h1>
		<a class="active" href="javascript:;" onclick="WorkoutPlan.search();" id="search-link">Search plans</a><span> or</span>
		<a href="javascript:;" onclick="WorkoutPlan.addWorkoutPlan();" id="add-workout-plan-link">Create new plan</a><span> or</span>
	 	<a href="javascript:;" onclick="WorkoutPlan.addWorkoutPlanSet();" id="add-workout-plan-set-link">Training plan set</a>
	</h1>
	<div id="shareContent">
		<?php echo $this->action('show-search-form', 'workout', null, array (
			'name' => $this->name
		))?>
	</div>
</div>

<style>
.span-tr,.span-trrow,.span-trimage,.span-trname {float:left; margin-right:10px;}
.last {margin-right:0;}
.span-tr {width:663px; overflow: hidden;}
.span-trrow {width:325px; background-color: #EBEBEB;}
.span-trrow h1 {margin:5px 0 10px 5px; font-size:16px;}
.span-trimage {margin:0 10px 10px 5px; width:60px;}
.span-trname {width:245px;}
.tr-preview {position:absolute; bottom:15px; left:75px;}
.tr-sameheight {padding-bottom: 1000px; margin-bottom:-1000px;}
.tr-relatvie {margin-bottom:5px; position:relative;}
</style>

<div class="block clear" style="background-color: white; padding-left:18px;padding-top:15px;border-top:0;">
	<h1>Top <span style="color: #1BD7F2;">Workout</span> Plans</h1>
	<div class="span-tr">
		<div class="span-trrow tr-sameheight" style="margin-right: 5px;">

			<div class="span-trrow"><h1>Top half-marathon workouts</h1></div>
			<?php foreach ($this->top_running_workout_21 as $workout) { ?>
			<div class="span-trrow tr-relatvie">
					<div class="span-trimage"><a href="workout?sets=<?php echo $workout['id'];?>" title="Preview Workout"><img width=60px src="<?=$workout['image'];?>" title="<?=$workout['name'];?>"></a></div>
					<div class="span-trname last">
						<div class="span-trname">
							<a href="workout?sets=<?php echo $workout['id'];?>" title="Preview Workout"><?=$workout['name'];?></a>
						</div>
						<div class="span-trname tr-preview last">
							<span style="color: #1BD7F2;"><a href="workout?sets=<?php echo $workout['id'];?>" title="Preview Workout">Preview Workout</a></span>
						</div>
					</div>
			</div>
			<?php } ?>

			<div class="span-trrow"><h1>Top 10km workouts</h1></div>
			<?php foreach ($this->top_running_workout_10 as $workout) { ?>
			<div class="span-trrow tr-relatvie">
					<div class="span-trimage"><a href="workout?sets=<?php echo $workout['id'];?>" title="Preview Workout"><img width=60px src="<?=$workout['image'];?>" title="<?=$workout['name'];?>"></a></div>
					<div class="span-trname last">
						<div class="span-trname">
							<a href="workout?sets=<?php echo $workout['id'];?>" title="Preview Workout"><?=$workout['name'];?></a>
						</div>
						<div class="span-trname tr-preview last">
							<span style="color: #1BD7F2;"><a href="workout?sets=<?php echo $workout['id'];?>" title="Preview Workout">Preview Workout</a></span>
						</div>
					</div>
			</div>
			<?php } ?>

		</div>
		<div class="span-trrow last tr-sameheight" style="margin-left: 5px;">
			<div class="span-trrow"><h1>Top coaches</h1></div>
			<?php foreach ($this->top_coaches as $coach) { ?>
			<div class="span-trrow tr-relatvie">
					<div class="span-trimage"><a href="workout?coach=<?php echo $coach['user']->getName()?>" title="Show Workouts"><img width=60px src="<?php echo $coach['user']->getProfileImageUrl()?>" title="<?php echo $coach['user']->getName()?>"></a></div>
					<div class="span-trname last">
						<div class="span-trname">
							<a href="workout?coach=<?php echo $coach['user']->getName()?>" title="Show Workouts"><?php echo $coach['user']->getName()?></a>
						</div>
						<div class="span-trname tr-preview last">
							<span style="color: #1BD7F2;"><a href="workout?coach=<?php echo $coach['user']->getName()?>" title="Show Workouts">Show Workouts</a></span>
						</div>
					</div>
			</div>
			<?php } ?>
		</div>
	</div>
</div>

<script type="text/javascript">
	Pager.init('#trainingPlanPosts', '/workout/posts/type/<?php echo $this->type?>/name/<?php echo $this->name?>/search/<?php echo $this->search?>');
	if (gup()=='plan') WorkoutPlan.addWorkoutPlanSet();
	//$("#contentWrapper").css("background-color","#EBEBEB")
</script>