<?php if (!$this->no_output) { ?>

<div class="block clear" style="background-color: white; padding-left:18px;padding-top:15px;border-top:0;padding-bottom:10px;">
<div id="trainingPlanPosts">

<style>
#nw_calendar {
	margin-right:30px;
	float: right;
	width: 170px;
	height: 45px;
	margin-top: -15px;
	text-align: center;
}
#nw_image {
	margin-right:-110px;
	margin-top: -135px;
	float: right;
}
#nw_left, #nw_right {
	cursor: pointer;
}
.open p {
	width: 440px !important;
}
.open p.sub {
	margin-left: 26px;
}
</style>

<h1><span style="color: #1BD7F2;">Workouts</span> Plan<?php if (count($this->trainingPlans)>1) { ?>s<?php } ?></h1>

<?php if (empty($this->trainingPlans)) { ?>
No workouts plan found.
<?php } else { ?>
<?php foreach ($this->trainingPlans as $trainingPlan) { ?>

<?php $details = $trainingPlan->getDetails(); ?>

<div class="block clear" style="background-color: white;" id="workout_next">
	<div class="content" style="padding: 13px 0 10px 0;">
		<div class="clear">
			<div class="goal">
		    	<h1 style="margin: 0 0 2px 0;font-size: 16px;margin-bottom:3px;"><?php echo $trainingPlan->getName();?></h1>
		    	<h2 style="margin: 0 0 2px 0;margin-bottom:3px;text-transform: none;">Event: <span style="color: #1BD7F2;"><?php echo $trainingPlan->getEvent();?></span> (<?php echo $trainingPlan->getEventDate()->format('d M Y')?>)</h2>
		    	<h2 style="margin: 0 0 2px 0;margin-bottom:3px;text-transform: none;">Sport: <span style="color: #1BD7F2;"><?php echo $trainingPlan->getSport()->getName();?> <?php echo $trainingPlan->getDistance();?></span></h2>
		    	<h2 style="margin: 0 0 2px 0;margin-bottom:3px;text-transform: none;">Intensity: <span style="color: #1BD7F2;"><?php echo $details['intensity'];?></span></h2>
		    	<h2 style="margin: 0 0 2px 0;margin-bottom:3px;text-transform: none;">Coach: <span style="color: #1BD7F2;"><?php echo $trainingPlan->getUser()->getName();?></span></h2>
		    	<h2 style="color: #CCC;margin: 0 0 2px 0;margin-bottom:10px;text-transform: none;">Currently use: <span style="color: #F2491B;"><?php echo $trainingPlan->getUsage();?></span> Likes: <span style="color: #F2491B;"><?php echo $trainingPlan->getLikes();?></span></h2>
		    		<div id="nw_calendar">
		    			<?php if ($details['nr']==1) { ?>
						<img src="/gfx/arrow_left.png">
		    			<?php } else { ?>
		    			<a href="?sets=<?php echo $trainingPlan->getId();?>&nr=<?php echo $details['nr']-1;?>"><img src="/gfx/arrow_left_active.png"></a>
		    			<?php } ?>
		    			<span style="font-size: 26px;" id="nw_workout_execution_order"><?=$details['nr'];?>/<?=$details['max_nr'];?></span>

		    			<?php if ($details['nr']==$details['max_nr']) { ?>
						<img src="/gfx/arrow_right.png">
		    			<?php } else { ?>
		    			<a href="?sets=<?php echo $trainingPlan->getId();?>&nr=<?php echo $details['nr']+1;?>"><img src="/gfx/arrow_right_active.png"></a>
		    			<?php } ?>

		    			<br>
		        		<span style="font-size: 12px;" id="nw_workout_days_between"><?=$details['days_between_html'];?></span>
		    		</div>
				<h1 id="nw_workout_name"><?=$details['kopa_html'];?> <?=$details['name'];?></h1>
			</div>
		</div>
		<div class="workoutBarWrapper">
			<div class="workoutBar clear" id="nw_workout_graph">
				<?=$details['workout_graph'];?>
			</div>
		</div>
		<div id="nw_image">
			<input style="margin-bottom:20px;" type="button" class="button clear buttonActive" id="submitButtonSet_<?php echo $trainingPlan->getId();?>" value="Start training" onClick="javascript:startTraining(<?php echo $trainingPlan->getId();?>)">
			<img width=150px class="clear" title="<?php echo $trainingPlan->getEvent();?>" src="<?php echo $trainingPlan->getImage();?>">
			<!--<img style="padding-top:20px;margin-right:30px;" class="right" title="Send to iCal or mail" src="/partner/icons.jpg">-->
		</div>
		<div class="showMore clear open">
			<div class="" id="nw_workout_text">
				<?=$details['workout_text'];?>
        	</div>
		</div>
	</div>
</div>

<?php } ?>
<?php } ?>

<script>

function startTraining(plan_id) {
	$('.button').addClass("buttonNoActive");
	$('.button').attr("disabled", "true");
	$.post('/news-feed/add-training-plan-set', { setSetsId: plan_id }, function (result) {
		window.location = "/news-feed"
	});
}		

</script>
</div>
</div>

<?php } ?>