<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php echo $this->headTitle() ?>
<?php echo $this->headMeta()?>
<?php echo $this->headLink()?>
<?php echo $this->headScript()?>
<script type="text/javascript">
	baseUrl = '<?php echo $this->baseUrl()?>';
</script>
<style type="text/css">
	html {
		background: url(/gfx/bg_00.png) repeat;
	}
</style>

</head>
<body id="liveTracking">
	<div class="container">
		<?php echo $this->action('header', 'layout')?>
	</div>
	<?php echo $this->layout()->content?>
	
	<div class="container">
		<div id="footer">
			<span>©2011 Trainingbook - All rights reserved</span>
			<ul>
				<li><a href="javascript:;" onclick="Modal.open('#about');">Contact</a></li>
				<!-- li><a href="javascript:;" onclick="Modal.open('#support');">Support</a></li> -->
				<?php /*?><li><a href="javascript:;" onclick="Modal.open('#terms');">Terms &amp; Policy</a></li><?php */ ?>
			</ul>
		</div>
	</div>
	
	<div id="modal">
		<?php echo $this->action('terms', 'page')?>
		<?php echo $this->action('support', 'page')?>
		<?php echo $this->action('about', 'page')?>
	</div>
	<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-28972354-1']);
  _gaq.push(['_setDomainName', 'trainingbook.com']);
  _gaq.push(['_setAllowLinker', true]);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl&#39; : 'http://www&#39;) + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</body>
</html>
