<div class="signIn hidden">
	<h1>Create your account </h1>
	<p class="or">or sign in</p>
	<div class="line"></div>
	<div class="withFacebook"><a href="/user/login/type/facebook">with Facebook</a></div>
	<div class="withTwitter"><a href="/user/login/type/twitter">with Twitter</a></div>
	<p>By creating an account you accept Trainingbook <a href="javascript:;" onclick="Modal.open('#terms');">Terms & Policy</a>  and so and other legal and illegal stuff if needed</p>
</div>