<div id="top" class="clear">
	<h1>
		<span>+ Your next </span> 
		<a href="javascript:;" id="share-workout-link">Workout</a>
	</h1>
</div>	

<?php
	function sec2hms ($sec)
	{
	$hms = "";
	$hours = intval(intval($sec) / 3600);
	$hms .= str_pad($hours, 2, "0", STR_PAD_LEFT). ':';
	$minutes = intval(($sec / 60) % 60);
	$hms .= str_pad($minutes, 2, "0", STR_PAD_LEFT). ':';
	$seconds = intval($sec % 60);
	$hms .= str_pad($seconds, 2, "0", STR_PAD_LEFT);
	
	return $ms.$hms;
	}
	  $intensity=array('','Low intensity','Medium intensity','High intensity','');
	  
	  $db = Zend_Db_Table::getDefaultAdapter();
    $user_id = $this->currentUser->getId();

	  $data = $db->fetchAll("SELECT * FROM UserConfig where user_id=$user_id and param_name='TrainingPlan'");
    
if (isset($data[0])) {
      
      $treninu_plans = $data[0];
   	
	    $data = $db->fetchAll("SELECT Sport.Name sport_name, TrainingPlan.name name, TrainingPlan.id, date_format(TrainingPlan.date,'%W, %d %M, %Y') date FROM TrainingPlan, Sport where TrainingPlan.sport_id=Sport.id and TrainingPlan.user_id=$user_id and (date(TrainingPlan.date)=curdate() or TrainingPlan.date>now()) order by TrainingPlan.date asc limit 1");
      $treninu_workout = $data[0];

      $data = $db->fetchAll("SELECT * FROM Exercise, Goal where  Exercise.goal_id=Goal.id and trainingPlanId = '".$treninu_workout['id']."'");
  	  
  	  //echo "<pre>";
  	  //print_r($data);
  	  //echo "</pre>";
    	
    	$goal_column='distance';
    	if ($data[0]['duration'] <> 0) {
      	$goal_column='duration';
    	}
    	
    	//visu sareekinam un samapojam
    	$kopa = 0;
    	foreach ($data as $row) {
    		$kopa=$kopa+$row[$goal_column];
    	}
    	if ($goal_column=='distance') {
      	$kopa_html = ($kopa/1000)." km";
      } else {
      	$kopa_html = sec2hms($kopa);
      }
?>

<div class="block clear" style="background-color: white; padding-left:18px;">
		<div class="content" style="padding: 13px 0 10px 0;">
			<div class="clear">
				<div class="goal">
			    <h1 style="margin: 0 0 2px 0;"><?=$treninu_plans['param_value'];?></h1>
					<h2 style="margin: 0px 0 0 0;text-transform: none;font-weight: normal;"><?=$treninu_workout['date'];?> - <?=$treninu_workout['sport_name'];?></h2>
					<h1><?=$kopa_html;?> <?=$treninu_workout['name'];?></h1>
									</div>
			</div>
			<div class="workoutBarWrapper">
				<div class="workoutBar clear">
	        <?php $i=0; foreach ($data as $row) { ?>
	        <?php if ($row['intensity']==4) $row['intensity']=0; ?>
  				<div style="width: <?=($row[$goal_column]*100/$kopa);?>%;" class="workout0<?=($row['intensity']+1);?><?php if ($i==0) { ?> first<?php } ?><?php if ($i==count($data)-1) { ?> last<?php } ?>">
  				  <?php if ($i<>count($data)-1) { ?><span></span><?php } ?>
  				</div>
	        <?php $i++; } ?>
				</div>
			</div>
			<div class="showMore clear open">
				<div class="">
	        <?php $i=0; foreach ($data as $row) { ?>
    	      <?php
    	      $class="class=\"sub\"";
    	      if ($i==0 or $i==count($data)-1) {$class="";}
    	      if ($goal_column=='distance') {
            	$goal_html = ($row['distance']/1000)." km";
            } else {
            	$goal_html = sec2hms($row['duration']);
            } ?>
	 			    <p <?=$class;?>><?=$goal_html;?> <?=$row['name'];?> <b><?=$intensity[$row['intensity']];?></b> <span class="infoText"> <?=$row['note'];?></span></p>
          <?php $i++; } ?>
				</div>
			</div>
		</div>
</div>	

<?php }  else { ?>
<style> a#nohover:hover { text-decoration: none;} </style> 
<div class="block clear" style="background-color: white; padding-left:38px;">
		<div class="content" style="padding: 13px 0 10px 0;color: #CCC; font-size: 22px; font-weight: bold;text-decoration: none;">
<a href="\workout#plan" title="Choose a workout plan to achieve your fitness goals!" id="nohover">Choose a workout plan to achieve your fitness goals!</a>
		</div>
</div>	

<?php } ?>

<div id="top" class="clear">
	<h1>
		<span>+ Add a </span>
		<a href="javascript:;" onclick="ShareContent.note();" id="share-note-link">Note</a><span>,</span>
		<a href="javascript:;" onclick="ShareContent.photo();" id="share-photo-link">Photo</a>
		<span>or</span>
		<a href="javascript:;" onclick="ShareContent.workout();" id="share-workout-link">Workout</a>
	</h1>
	<form method="post" id="shareContentForm" enctype="multipart/form-data">
		<div id="shareContent"></div>
		<div class="shareAction" style="display: none;">
			<span>
				<input type="radio" id="share-social" name="isPrivate" value="0" checked="checked" />
				<label class="active" for="share-social">Share:</label>
			</span>
			<span>
				<?php if ($this->currentUser->getFacebookUserId() != null):?>
					<a href="javascript:;" id="share-facebook" class="facebook facebookActive" onclick="$('#share-social').attr('checked', 'checked');">Facebook</a>
					<input type="hidden" name="postFacebook" id="post-facebook" value="1" />
				<?php endif;?>
				<?php if ($this->currentUser->getTwitterUserId() != null):?>
					<a href="javascript:;" id="share-twitter" class="twitter twitterActive" onclick="$('#share-social').attr('checked', 'checked');">Twitter</a>
					<input type="hidden" name="postTwitter" id="post-twitter" value="1" />
				<?php endif;?>
			</span>
			<span>
				<input type="radio" id="private-share" name="isPrivate" value="1" />
				<label for="private-share">Private</label>
			</span>
			<input type="button" class="button right" name="publish" id="publishButton" value="Add" onclick="$(this).click(function (){$(this).attr('disabled', true)});"/>
		</div>
	</form>
	<div class="tabs">
		<ul>
			<li<?php if ($this->type == null):?> class="active"<?php endif;?>><a href="/news-feed">Friends activity</a></li>
			<li<?php if ($this->type == 'my'):?> class="active"<?php endif;?>><a href="/news-feed/index/type/my">My activity</a></li>
			<!-- <li<?php if ($this->type == 'public'):?> class="active"<?php endif;?>><a href="/news-feed/index/type/public">Public feed</a></li> -->
		</ul>
	</div>
</div>
<div id="newsFeedPosts">
	<?php echo $this->action('posts', 'news-feed', null, array (
		'type' => $this->type,
	))?>
</div>

<div class="block clear noBord">
	<div class="more">
		<a href="javascript:;" id="load-more">Load More News</a>
		<input type="hidden" name="typeValue" id="typeValue" value="<?php echo $this->type?>" />
	</div>
</div>
<script type="text/javascript">
	$(document).ready(function() {
		ShareContent.init();
		NewsFeed.init();
	});
</script>