<table>
	<tr>
		<?php for ($i = 3; $i >= 0; $i--):?>
			<td class="graph">
				<?php if (isset($this->workouts[$i]['workout'])):?>
					<span><?php echo $this->workouts[$i]['workout']?></span>
					<div class="graph">
						<img  style="height: <?php echo $this->workouts[$i]['percent']?>px" alt="" src="/gfx/bar_small_bg.png" />
					</div>
				<?php endif;?>
			</td>
		<?php endfor;?>
	</tr>
	<tr>
		<?php for ($i = 3; $i >= 1; $i--):?>
			<td>
				<?php if (isset($this->workouts[$i]['week'])):?>
					W<?php echo $this->workouts[$i]['week']?>
				<?php endif;?>
			</td>
		<?php endfor;?>
		<td>Current</td>
	</tr>
</table>