<?php

namespace proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntityExerciseRaportProxy extends \Entity\Exercise\Raport implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getDistance()
    {
        $this->__load();
        return parent::getDistance();
    }

    public function setDistance($distance)
    {
        $this->__load();
        return parent::setDistance($distance);
    }

    public function getStartTime()
    {
        $this->__load();
        return parent::getStartTime();
    }

    public function setStartTime($startTime)
    {
        $this->__load();
        return parent::setStartTime($startTime);
    }

    public function getEndTime()
    {
        $this->__load();
        return parent::getEndTime();
    }

    public function setEndTime($endTime)
    {
        $this->__load();
        return parent::setEndTime($endTime);
    }

    public function getWorkout()
    {
        $this->__load();
        return parent::getWorkout();
    }

    public function setWorkout(\Entity\Workout $workout)
    {
        $this->__load();
        return parent::setWorkout($workout);
    }

    public function getExercise()
    {
        $this->__load();
        return parent::getExercise();
    }

    public function setExercise($exercise)
    {
        $this->__load();
        return parent::setExercise($exercise);
    }

    public function getTrackPoints()
    {
        $this->__load();
        return parent::getTrackPoints();
    }

    public function setTrackPoints($trackPoints)
    {
        $this->__load();
        return parent::setTrackPoints($trackPoints);
    }

    public function addTrackPoint(\Entity\Exercise\TrackPoint $trackPoint)
    {
        $this->__load();
        return parent::addTrackPoint($trackPoint);
    }

    public function populate(array $values)
    {
        $this->__load();
        return parent::populate($values);
    }

    public function toArray()
    {
        $this->__load();
        return parent::toArray();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'distance', 'startTime', 'endTime', 'workout', 'exercise', 'trackPoints');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}