<?php

namespace proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntityTrainingPlanProxy extends \Entity\TrainingPlan implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getDate()
    {
        $this->__load();
        return parent::getDate();
    }

    public function setDate($date)
    {
        $this->__load();
        return parent::setDate($date);
    }

    public function getExecutionOrder()
    {
        $this->__load();
        return parent::getExecutionOrder();
    }

    public function setExecutionOrder($executionOrder)
    {
        $this->__load();
        return parent::setExecutionOrder($executionOrder);
    }

    public function getDeletedTime()
    {
        $this->__load();
        return parent::getDeletedTime();
    }

    public function setDeletedTime($deletedTime)
    {
        $this->__load();
        return parent::setDeletedTime($deletedTime);
    }

    public function getUser()
    {
        $this->__load();
        return parent::getUser();
    }

    public function setUser($user)
    {
        $this->__load();
        return parent::setUser($user);
    }

    public function getWorkouts()
    {
        $this->__load();
        return parent::getWorkouts();
    }

    public function setWorkouts($workouts)
    {
        $this->__load();
        return parent::setWorkouts($workouts);
    }

    public function getExercises()
    {
        $this->__load();
        return parent::getExercises();
    }

    public function setExercises($exercises)
    {
        $this->__load();
        return parent::setExercises($exercises);
    }

    public function addExercise(\Entity\Exercise $exercise)
    {
        $this->__load();
        return parent::addExercise($exercise);
    }

    public function countDistances()
    {
        $this->__load();
        return parent::countDistances();
    }

    public function countTime()
    {
        $this->__load();
        return parent::countTime();
    }

    public function populate(array $values)
    {
        $this->__load();
        return parent::populate($values);
    }

    public function toArray()
    {
        $this->__load();
        return parent::toArray();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'date', 'executionOrder', 'deletedTime', 'user', 'workouts', 'exercises');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}